[pytest]
filterwarnings =
    ignore:`torch\.jit\.script` is deprecated.*:DeprecationWarning
    ignore:.*'oneOf' deprecated - use 'one_of'.*:DeprecationWarning
    ignore:.*'parseString' deprecated - use 'parse_string'.*:DeprecationWarning
    ignore:.*'resetCache' deprecated - use 'reset_cache'.*:DeprecationWarning
    ignore:.*'enablePackrat' deprecated - use 'enable_packrat'.*:DeprecationWarning

# unified test directory
testpaths = test
